// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	repository "golang-test-task/internal/repository"
)

// PoolCreator is an autogenerated mock type for the PoolCreator type
type PoolCreator struct {
	mock.Mock
}

// NewPool provides a mock function with no fields
func (_m *PoolCreator) NewPool() (repository.DBAdapter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewPool")
	}

	var r0 repository.DBAdapter
	var r1 error
	if rf, ok := ret.Get(0).(func() (repository.DBAdapter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() repository.DBAdapter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.DBAdapter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPoolCreator creates a new instance of PoolCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPoolCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PoolCreator {
	mock := &PoolCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
