services:
  golang-test-app:
    build: 
      context: ../../
      dockerfile: deployments/Dockerfile
    restart: unless-stopped
    container_name: golang-test-app
    depends_on:
      postgres-service-db:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/config.yaml"
      TEST_APP_PORT: ${TEST_APP_PORT}
      POSTGRES_HOST: postgres-service-db
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SERVICE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SERVICE_DB}
      PGUSER: ${SERVICE_PGUSER}
    volumes:
      - ../../configs/config.yaml:/usr/local/src/configs/config.yaml:ro
    ports:
      - "${TEST_APP_PORT}:8080"
    networks:
      - myapp_network

  postgres-service-db:
    image: postgres:latest
    container_name: service_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SERVICE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SERVICE_DB}
      PGUSER: ${SERVICE_PGUSER}
    volumes:
      - postgres_service_data:/var/lib/postgresql
      - ../postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_SERVICE_PORT}:5432"
    networks:
      - myapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

    

networks:
  myapp_network:
    driver: bridge

volumes:
  postgres_service_data: